name: Android CI

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: '输入版本号'
        # Default value if no value is explicitly provided
        default: 'manual-latest'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string

jobs:
  build:

    runs-on: ubuntu-latest
    
    env:
      # 核心逻辑：如果有手动输入则用输入值，否则用 Git 引用名（分支/标签名）
      APK_TAG: ${{ github.event.inputs.name || github.ref_name }}
      APK_NAME: "notes"
      
    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assembleDebug
      
    - name: Upload Tarball
      uses: actions/upload-artifact@v5
      with:
        name: ${{ env.APK_NAME }}-${{ env.APK_TAG }}
        path: app/build/outputs/apk/debug/app-debug.apk
    