name: Docker Image CI

on:
  push:
    tags:
      - "v*" # 当推送到以 v 开头的标签（如 v1.0.1）时触发
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: '输入镜像版本号'
        # Default value if no value is explicitly provided
        default: 'manual-latest'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write # 必须赋予写入权限以创建 Release
    # 在这里定义整个 Job 通用的环境变量
    env:
      # 核心逻辑：如果有手动输入则用输入值，否则用 Git 引用名（分支/标签名）
      IMAGE_TAG: ${{ github.event.inputs.name || github.ref_name }}
      IMAGE_NAME: "notes"
    
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        FULL_NAME="${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}"
        FILENAME="${{ env.IMAGE_NAME }}-${{ env.IMAGE_TAG }}.tar.gz"
        echo "FULL_NAME=$FULL_NAME" >> $GITHUB_ENV
        echo "FILENAME=$FILENAME" >> $GITHUB_ENV

        docker build . --file Dockerfile --tag ${FULL_NAME}

        docker save ${FULL_NAME} | gzip > ${FILENAME}

    - name: Upload Tarball
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.FULL_NAME}}
        path: ${{ env.FILENAME }}

    # - name: Create GitHub Release
    #   uses: softprops/action-gh-release@v2
    #   with:
    #     files: ${{ env.FILENAME }}
    #     name: Release ${{ github.ref_name }}
    #     draft: false
    #     prerelease: false
    #     generate_release_notes: true # 自动生成变更日志
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}