name: Docker Image CI

on:
  push:
    tags:
      - "v*" # 当推送到以 v 开头的标签（如 v1.0.1）时触发
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Person to greet'
        # Default value if no value is explicitly provided
        default: 'World'
        # Input has to be provided for the workflow to run
        required: false
        # The data type of the input
        type: string

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        IMAGE_NAME="notes"
        TAG="${{ github.sha }}" 
        FULL_NAME="${IMAGE_NAME}:${TAG}"
        FILENAME="${IMAGE_NAME}-${TAG}.tar.gz"
        docker build . --file Dockerfile --tag ${FULL_NAME}

        docker save ${FULL_NAME} | gzip > ${FILENAME}

        echo "IMAGE_FILENAME=$FILENAME" >> $GITHUB_ENV

    - name: Upload Tarball
      uses: actions/upload-artifact@v4
      with:
        name: notes-image
        path: ${{ env.IMAGE_FILENAME }}

    # - name: Create GitHub Release
    #   uses: softprops/action-gh-release@v2
    #   with:
    #     files: notes-*.tar.gz
    #     name: Release ${{ github.ref_name }}
    #     draft: false
    #     prerelease: false
    #     generate_release_notes: true # 自动生成变更日志
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}